name: Build LaTeX PDF

on:
  push:
    branches: [main]
    paths:
      - '**/*.tex'
      - '**/*.bib'
      - '**/*.cls'
      - '**/*.png'
      - '**/*.jpg'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX environment and build PDF
        uses: dante-ev/latex-action@latest
        with:
          root_file: dx-real-analysis.tex
          compiler: xelatex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Real-Analysis-PDF
          path: dx-real-analysis.pdf
