name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-pdf:
    name: Compile LaTeX to PDF
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取最新代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 安装 TeX Live（包括 XeTeX、CTeX 字体等）和 Biber
      - name: Install TeX Live and Biber
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-bibtex-extra \
            biber \
            fonts-noto-cjk

      # 3. 第一遍 XeLaTeX 编译（生成 .aux 等文件）
      - name: First XeLaTeX compilation
        run: xelatex -interaction=nonstopmode dx-real-analysis.tex || true

      # 4. 用 Biber 处理参考文献
      - name: Run Biber
        run: biber dx-real-analysis || true

      # 5. 第二遍 XeLaTeX 编译（引用和目录）
      - name: Second XeLaTeX compilation
        run: xelatex -interaction=nonstopmode dx-real-analysis.tex || true

      # 6. 第三遍 XeLaTeX 编译（确保所有引用正确）
      - name: Final XeLaTeX compilation
        run: xelatex -interaction=nonstopmode dx-real-analysis.tex || true

      # 7. 上传生成的 PDF 作为 Artifact
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: dx-real-analysis-pdf
          path: dx-real-analysis.pdf
- name: List files after build
  run: |
    pwd
    ls -R
